[map_renderer]
# Objects inside this list will never render
hide_invisible = [
"/turf/",
"/obj/lattice",
"/obj/machinery/",
"/obj/cable/",
"/obj/decal/",
"/obj/firedoor_spawn",
"/obj/securearea",
"/obj/table/",
"/obj/disposalpipe/",
"/obj/submachine/",
"/obj/reagent_dispensers/",
"/obj/potted_plant",
"/obj/access_spawn/",
"/obj/storage/",
"/obj/grille/",
"/obj/warp_beacon",
"/obj/item/",
"/obj/window/",
"/obj/critter/",
"/obj/stool/",
"/obj/rack",
"/obj/shrub",
"/obj/railing/",
"/obj/indestructible/",
"/obj/npc/",
"/mob/",
"/obj/computer3frame/",
"/obj/structure/",
"/obj/forcefield/",
"/obj/noticeboard/",
"/obj/plasticflaps",
"/obj/tree",
"/obj/item_dispenser/",
"/obj/displaycase",
"/obj/xmastree/",
"/obj/atlasplaque",
"/obj/disposaloutlet",
"/obj/vehicle/",
"/obj/mopbucket",
"/obj/monkeyplant",
"/obj/bedsheetbin",
"/obj/health_scanner/",
"/obj/surgery_tray",
"/obj/voting_box",
"/obj/iv_stand",
"/obj/bookshelf/",
"/obj/fitness/",
"/obj/loudspeaker",
"/obj/cryotron",
"/obj/drink_rack/",
"/obj/kitchenspike",
"/obj/window_blinds/",
"/obj/blind_switch/",
"/obj/stove"
]
