[map_renderer]
# Objects inside this list will never render
hide_invisible = [
"/obj/xmastree/ephemeral",
"/obj/machinery/navbeacon/"
]

[map_renderer.fancy_layers]
"/obj/effects/background_objects/" = -15

"/obj/disposalpipe/" = -11
"/obj/machinery/atmospherics/pipe/simple/insulated" = -9
"/obj/machinery/atmospherics/binary/pump" = -9
"/obj/machinery/atmospherics/valve" = -9
"/obj/machinery/atmospherics/pipe/manifold" = -9
"/obj/machinery/atmospherics/pipe/simple/junction" = -9

"/obj/cable" = -10

"/obj/lattice" = -10
"/turf/simulated/wall/auto/reinforced/supernorn" = -8
"/turf/simulated/floor/plating/random" = -12

[map_renderer.render_passes]

only-pipenet = false